### PR TITLE
Fix dependencies in realsense_ros2_camera

### PR DESCRIPTION
**Pull request by clalancette**
I recently tried to run:

```
sudo apt-get install ros-dashing-realsense-ros2-camera
```

After doing that and then trying to run the camera with:
```
ros2 run realsense_ros2_camera realsense_ros2_camera
```

I get an error message:
```
/opt/ros/dashing/lib/realsense_ros2_camera/realsense_ros2_camera: error while loading shared libraries: libimage_transport.so: cannot open shared object file: No such file or directory
```

This is because the package.xml has a build dependency on image_transport, but forgets the exec dependency.  While I was in here, I did a bit of cleanup to remove unnecessary dependencies and make the tests pass.  This will likely conflict with some of the other open PRs, but I think this should probably go in first (and be released); otherwise, anyone trying to install the dashing packages will not have a good out-of-box experience.

### CODE REVIEW

**Comment by IanTheEngineer** [comment]
+1 to these changes. They fix the out-of-the-box apt-get error using ros2 and the realsense.

@sharronliu, @ahuizxc, & @yechun1 can you please take a look?

**Comment by yechun1** [comment]
@xhuan28 @ahuizxc would you please help to review the PR?

**Comment by clalancette** [comment]
@ahuizxc Thanks for the review.

@yechun1 Do you think this is ready for merge now?

**Comment by yechun1** [comment]
@clalancette thank you very much for fixing the issue.

**Pull request merged**
